version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/be"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/fe"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "develop"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "develop"
