import * as React from 'react'

import { cn } from '@/lib/utils'

/*
 * Generated by `shadcn add input`, with the project adaptation: the stock type and shadow scales are
 * reset in index.css, so shadcn's `text-base` / `md:text-sm` / `file:text-sm` become the DESIGN.md
 * `form-input` role (`text-body-sm`, 14px), the off-token `shadow-xs` is dropped (DESIGN inputs sit on
 * a hairline border, no shadow), and the height is `h-10` (40px, the DESIGN form-input height).
 * Re-apply these swaps if regenerated. Semantic classes resolve through the token bridge.
 */

function Input({ className, type, ...props }: React.ComponentProps<'input'>) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        'h-10 w-full min-w-0 rounded-md border border-input bg-transparent px-3 py-1 text-body-sm transition-[color,box-shadow] outline-none selection:bg-primary selection:text-primary-foreground file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-body-sm file:font-medium file:text-foreground placeholder:text-muted-foreground disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 dark:bg-input/30',
        'focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50',
        'aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40',
        className,
      )}
      {...props}
    />
  )
}

export { Input }
