import * as React from 'react'
import { Label as LabelPrimitive } from 'radix-ui'

import { cn } from '@/lib/utils'

/*
 * Generated by `shadcn add label`, with the project adaptation: the stock type scale is reset in
 * index.css, so shadcn's `text-sm leading-none font-medium` becomes the DESIGN.md `text-body-sm-strong`
 * role (14px / 500, line-height bundled). Re-apply this swap if regenerated.
 */

function Label({ className, ...props }: React.ComponentProps<typeof LabelPrimitive.Root>) {
  return (
    <LabelPrimitive.Root
      data-slot="label"
      className={cn(
        'flex items-center gap-2 text-body-sm-strong select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50',
        className,
      )}
      {...props}
    />
  )
}

export { Label }
