import * as React from 'react'

import { cn } from '@/lib/utils'

/*
 * Generated by `shadcn add textarea`, with the project adaptation (matching input.tsx): the stock type
 * and shadow scales are reset in index.css, so shadcn's `text-base` / `md:text-sm` become the DESIGN.md
 * `form-input` role (`text-body-sm`, 14px) and the off-token `shadow-xs` is dropped (DESIGN inputs sit
 * on a hairline border, no shadow). Re-apply these swaps if regenerated.
 */
function Textarea({ className, ...props }: React.ComponentProps<'textarea'>) {
  return (
    <textarea
      data-slot="textarea"
      className={cn(
        'flex field-sizing-content min-h-16 w-full rounded-md border border-input bg-transparent px-3 py-2 text-body-sm transition-[color,box-shadow] outline-none placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:bg-input/30 dark:aria-invalid:ring-destructive/40',
        className,
      )}
      {...props}
    />
  )
}

export { Textarea }
